services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.13.40
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP порт
      - "9000:9000" # Native TCP порт

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"

